Implement as proc-macro (WIP)
Fundament-Software/capnp-import pull request #11
Opened 2023-06-04 23:41 UTC by ugandalf

Closes #3. I think it's basically working, but still has some problem parts / todos:
- Clean up messy code, remove artifacts
- Make proper tests
- Currently, it doesn't support two capnp files with the same name - should we support that?
- (Potentially not in scope of this issue) Build times seem awfully long in actions
- Document usage and increment version number (as it's a breaking change)

2023-06-21 07:56 UTC, ErikMcClure requested changes

2023-06-21 07:56 UTC, ErikMcClure commented on src/lib.rs
> +        println!("Processing path: {:?}", entry.to_str());
Unfortunately, proc macros do not like it when you print things. Proc macro diagnostics were never stabilized, so there is no better way to debug them, so we should comment out these print statements after development is finished, but leave the commented lines in the code for debugging later.

2023-06-21 07:56 UTC, ErikMcClure commented on src/lib.rs
> +    let module_name = format_ident!("{}", file_stem);
I tested, and it turns out that invoking the capnproto command will always produce `thefilename_capnp` regardless of what the extension is. Here, we should look for `_capnp` in the file stem and remove it.

2023-06-21 07:56 UTC, ErikMcClure commented on src/lib.rs
> +        mod #module_name {
We should generate an enclosing `mod #path_part {` for every folder in the _relative path_, which will fix the name problem.

2023-06-21 07:56 UTC, ErikMcClure commented on src/lib.rs
> +    assert!(contents.starts_with("mod example_capnp {"));
should be changed to (may have to acquire the proper line ending depending on what rust does):

```
assert!(contents.starts_with("mod tests {\nmod example {"));
```

2023-06-21 22:51 UTC, ugandalf commented on src/lib.rs
> +    let module_name = format_ident!("{}", file_stem);
Looks like `_capnp` suffix is hardcoded for module names as evidenced by https://docs.rs/capnpc/0.14.0/src/capnpc/codegen.rs.html#73 - it's used internally in the generated code.

2023-06-21 22:54 UTC, ErikMcClure commented on src/lib.rs
> +    let module_name = format_ident!("{}", file_stem);
Ugh, we may change this later when we fork capnproto-rust but let's just leave it alone for now.

2023-06-21 22:57 UTC, ugandalf commented on src/lib.rs
> +        mod #module_name {
I encountered that `folder-test` is not a valid module name and changed it so that it replaces `-` with `_`. I doubt that's comprehensive (people might put spaces or other characters) - any other variants we want to handle?

2023-06-21 23:24 UTC, ErikMcClure commented on src/lib.rs
> +        mod #module_name {
We can use a cargo crate called convert_case https://docs.rs/convert_case/latest/convert_case/enum.Case.html which will handle all of this for us if we just convert it to snake_case.

2023-06-26 01:51 UTC, ugandalf commented on src/lib.rs
> +                .replace("-", "_")
I thought adding a crate for that was excessive, but since then saw that it makes sense. In the latest commit I switched to use it.

2023-06-26 02:02 UTC, ErikMcClure approved these changes

2023-06-26 02:03 UTC, merged